name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: py-${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: "3.11"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
      - name: Set Python path
        run: |
          echo "PYTHONPATH=." >> $GITHUB_ENV
      - name: Test
        run: |
          pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          name: ${{ matrix.python }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  examples:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ../
          pip install -r ../tests/requirements.txt

      - name: Run tests on example modules
        # We can't (yet) let pytest collect all the modules, since
        # we can't instantiate nanodjango.Django more than once (due to
        # django-ninja).
        run: |
          for module in "counter" "hello_async" "hello_world"; do
            echo "Test $module"
            nanodjango manage ${module}.py makemigrations ${module}
            pytest ${module}.py --cov-append
          done

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
